// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: whitelist_service.proto

package whitelistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddIPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpNetwork *IPNetwork `protobuf:"bytes,1,opt,name=ip_network,json=ipNetwork,proto3" json:"ip_network,omitempty"`
}

func (x *AddIPRequest) Reset() {
	*x = AddIPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whitelist_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIPRequest) ProtoMessage() {}

func (x *AddIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIPRequest.ProtoReflect.Descriptor instead.
func (*AddIPRequest) Descriptor() ([]byte, []int) {
	return file_whitelist_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddIPRequest) GetIpNetwork() *IPNetwork {
	if x != nil {
		return x.IpNetwork
	}
	return nil
}

type AddIPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *AddIPResponse) Reset() {
	*x = AddIPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whitelist_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIPResponse) ProtoMessage() {}

func (x *AddIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIPResponse.ProtoReflect.Descriptor instead.
func (*AddIPResponse) Descriptor() ([]byte, []int) {
	return file_whitelist_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddIPResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RemoveIPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpNetwork *IPNetwork `protobuf:"bytes,1,opt,name=ip_network,json=ipNetwork,proto3" json:"ip_network,omitempty"`
}

func (x *RemoveIPRequest) Reset() {
	*x = RemoveIPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whitelist_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIPRequest) ProtoMessage() {}

func (x *RemoveIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIPRequest.ProtoReflect.Descriptor instead.
func (*RemoveIPRequest) Descriptor() ([]byte, []int) {
	return file_whitelist_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveIPRequest) GetIpNetwork() *IPNetwork {
	if x != nil {
		return x.IpNetwork
	}
	return nil
}

type RemoveIPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *RemoveIPResponse) Reset() {
	*x = RemoveIPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whitelist_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIPResponse) ProtoMessage() {}

func (x *RemoveIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIPResponse.ProtoReflect.Descriptor instead.
func (*RemoveIPResponse) Descriptor() ([]byte, []int) {
	return file_whitelist_service_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveIPResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetIpListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetIpListRequest) Reset() {
	*x = GetIpListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whitelist_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIpListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpListRequest) ProtoMessage() {}

func (x *GetIpListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpListRequest.ProtoReflect.Descriptor instead.
func (*GetIpListRequest) Descriptor() ([]byte, []int) {
	return file_whitelist_service_proto_rawDescGZIP(), []int{4}
}

type GetIPListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpNetwork []*IPNetwork `protobuf:"bytes,1,rep,name=ip_network,json=ipNetwork,proto3" json:"ip_network,omitempty"`
}

func (x *GetIPListResponse) Reset() {
	*x = GetIPListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whitelist_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIPListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPListResponse) ProtoMessage() {}

func (x *GetIPListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPListResponse.ProtoReflect.Descriptor instead.
func (*GetIPListResponse) Descriptor() ([]byte, []int) {
	return file_whitelist_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetIPListResponse) GetIpNetwork() []*IPNetwork {
	if x != nil {
		return x.IpNetwork
	}
	return nil
}

var File_whitelist_service_proto protoreflect.FileDescriptor

var file_whitelist_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x77, 0x68, 0x69, 0x74, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x1a, 0x17, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a,
	0x0c, 0x41, 0x64, 0x64, 0x49, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a,
	0x0a, 0x69, 0x70, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x49, 0x50,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x09, 0x69, 0x70, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x22, 0x1f, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x22, 0x46, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x50, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x69, 0x70, 0x5f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x77, 0x68, 0x69,
	0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x49, 0x50, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x52, 0x09, 0x69, 0x70, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x22, 0x0a, 0x10, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22,
	0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x49, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x49, 0x50, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x69, 0x70, 0x5f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x77,
	0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x49, 0x50, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x52, 0x09, 0x69, 0x70, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x32, 0xdd, 0x01,
	0x0a, 0x10, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x41, 0x64, 0x64, 0x49, 0x70, 0x12, 0x17, 0x2e, 0x77, 0x68,
	0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x50, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x41, 0x64, 0x64, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x08, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x70, 0x12, 0x1a, 0x2e, 0x77, 0x68, 0x69,
	0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x50, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x49, 0x70, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1b, 0x2e, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x49, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x50, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x27, 0x5a,
	0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x68, 0x69, 0x74, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_whitelist_service_proto_rawDescOnce sync.Once
	file_whitelist_service_proto_rawDescData = file_whitelist_service_proto_rawDesc
)

func file_whitelist_service_proto_rawDescGZIP() []byte {
	file_whitelist_service_proto_rawDescOnce.Do(func() {
		file_whitelist_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_whitelist_service_proto_rawDescData)
	})
	return file_whitelist_service_proto_rawDescData
}

var file_whitelist_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_whitelist_service_proto_goTypes = []interface{}{
	(*AddIPRequest)(nil),      // 0: whitelist.AddIPRequest
	(*AddIPResponse)(nil),     // 1: whitelist.AddIPResponse
	(*RemoveIPRequest)(nil),   // 2: whitelist.RemoveIPRequest
	(*RemoveIPResponse)(nil),  // 3: whitelist.RemoveIPResponse
	(*GetIpListRequest)(nil),  // 4: whitelist.GetIpListRequest
	(*GetIPListResponse)(nil), // 5: whitelist.GetIPListResponse
	(*IPNetwork)(nil),         // 6: whitelist.IPNetwork
}
var file_whitelist_service_proto_depIdxs = []int32{
	6, // 0: whitelist.AddIPRequest.ip_network:type_name -> whitelist.IPNetwork
	6, // 1: whitelist.RemoveIPRequest.ip_network:type_name -> whitelist.IPNetwork
	6, // 2: whitelist.GetIPListResponse.ip_network:type_name -> whitelist.IPNetwork
	0, // 3: whitelist.WhiteListService.AddIP:input_type -> whitelist.AddIPRequest
	2, // 4: whitelist.WhiteListService.RemoveIP:input_type -> whitelist.RemoveIPRequest
	4, // 5: whitelist.WhiteListService.GetIPList:input_type -> whitelist.GetIpListRequest
	1, // 6: whitelist.WhiteListService.AddIP:output_type -> whitelist.AddIPResponse
	3, // 7: whitelist.WhiteListService.RemoveIP:output_type -> whitelist.RemoveIPResponse
	5, // 8: whitelist.WhiteListService.GetIPList:output_type -> whitelist.GetIPListResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_whitelist_service_proto_init() }
func file_whitelist_service_proto_init() {
	if File_whitelist_service_proto != nil {
		return
	}
	file_whitelist_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_whitelist_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddIPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whitelist_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddIPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whitelist_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveIPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whitelist_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveIPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whitelist_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIpListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whitelist_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIPListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_whitelist_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whitelist_service_proto_goTypes,
		DependencyIndexes: file_whitelist_service_proto_depIdxs,
		MessageInfos:      file_whitelist_service_proto_msgTypes,
	}.Build()
	File_whitelist_service_proto = out.File
	file_whitelist_service_proto_rawDesc = nil
	file_whitelist_service_proto_goTypes = nil
	file_whitelist_service_proto_depIdxs = nil
}
