version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - db
    ports:
      - "80:${HTTP_PORT:-80}"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "${JAEGER_AGENT_PORT:-16686}:16686"
      - "${JAEGER_AGENT_PORT_UDP:-6831}:6831/udp"

  structurizr:
    image: structurizr/lite
    container_name: structurizr
    volumes:
      - ./:/usr/local/structurizr
    ports:
      - "8080:8080"

  puml:
    image: plantuml/plantuml-server:jetty
    container_name: puml
    ports:
      - "8081:8080"
    environment:
      - BASE_URL=plantuml
      - PLANTUML_SECURITY_PROFILE=UNSECURE

volumes:
  db-data: