version: '3.7'

services:
  structurizr:
    image: structurizr/lite
    container_name: structurizr
    volumes:
      - ./:/usr/local/structurizr
    ports:
      - "8080:8080"

  puml:
    image: plantuml/plantuml-server:jetty
    container_name: puml
    ports:
      - "8081:8080"
    environment:
      - BASE_URL=plantuml
      - PLANTUML_SECURITY_PROFILE=UNSECURE

volumes:
  db-data: