// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=./mock_test.go -package=ratelimiter
//

// Package ratelimiter is a generated GoMock package.
package ratelimiter
