// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	network "github.com/MaxFando/rate-limiter/internal/domain/network"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddIP provides a mock function with given fields: ctx, _a1
func (_m *Service) AddIP(ctx context.Context, _a1 network.IpNetwork) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, network.IpNetwork) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetIPList provides a mock function with given fields: ctx
func (_m *Service) GetIPList(ctx context.Context) ([]network.IpNetwork, error) {
	ret := _m.Called(ctx)

	var r0 []network.IpNetwork
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]network.IpNetwork, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []network.IpNetwork); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]network.IpNetwork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveIP provides a mock function with given fields: ctx, _a1
func (_m *Service) RemoveIP(ctx context.Context, _a1 network.IpNetwork) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, network.IpNetwork) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
