// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=./mock_test.go -package=bucket
//

// Package bucket is a generated GoMock package.
package bucket

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteUnusedBucket mocks base method.
func (m *MockRepository) DeleteUnusedBucket(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteUnusedBucket", ctx)
}

// DeleteUnusedBucket indicates an expected call of DeleteUnusedBucket.
func (mr *MockRepositoryMockRecorder) DeleteUnusedBucket(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUnusedBucket", reflect.TypeOf((*MockRepository)(nil).DeleteUnusedBucket), ctx)
}

// ResetBucket mocks base method.
func (m *MockRepository) ResetBucket(ctx context.Context, requestValue string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetBucket", ctx, requestValue)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ResetBucket indicates an expected call of ResetBucket.
func (mr *MockRepositoryMockRecorder) ResetBucket(ctx, requestValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetBucket", reflect.TypeOf((*MockRepository)(nil).ResetBucket), ctx, requestValue)
}

// TryGetPermissionInBucket mocks base method.
func (m *MockRepository) TryGetPermissionInBucket(ctx context.Context, requestValue string, limit int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryGetPermissionInBucket", ctx, requestValue, limit)
	ret0, _ := ret[0].(bool)
	return ret0
}

// TryGetPermissionInBucket indicates an expected call of TryGetPermissionInBucket.
func (mr *MockRepositoryMockRecorder) TryGetPermissionInBucket(ctx, requestValue, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryGetPermissionInBucket", reflect.TypeOf((*MockRepository)(nil).TryGetPermissionInBucket), ctx, requestValue, limit)
}
