name: Rate Limiter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO111MODULE: "on"

jobs:
  tests:
    name: Run Tests with Makefile
    runs-on: ubuntu-latest
    steps:
      # Проверяем код из репозитория
      - name: Checkout Code
        uses: actions/checkout@v3

      # Настраиваем Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      # Запуск тестов
      - name: Run Tests
        run: make test
  
  deploy:
    name: Deploy to Remote Host
    runs-on: ubuntu-latest
    needs:
      - tests
    if: github.ref == 'refs/heads/main'
    steps:
      # Проверяем код из репозитория
      - name: Checkout Code
        uses: actions/checkout@v3

      # Настраиваем Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      # Деплой на удаленный хост
      - name: Deploy to Remote Host
        run: make deploy